#!/bin/bash

COMPOSE_FILE="/usr/share/X11/locale/en_US.UTF-8/Compose"
if [ ! -s "$COMPOSE_FILE" ]; then
  echo >&2 "ERROR: unable to locate system compose."
  exit 1
fi
echo "Writing new $HOME/.XCompose..."
sed -e 's,\xc4\x86,\xc3\x87,g' \
    -e 's,\xc4\x87,\xc3\xa7,g' <"$COMPOSE_FILE">"$HOME/.XCompose"

echo Done.
